name: news_buzz
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 #CupertinoIcons default added
  http: ^1.3.0 #For fetching data from APO
  shimmer: ^3.0.0 #For shimmer effect while data is loading
  flutter_dotenv: ^5.2.1 #For loading environment variables from .env file
  flutter_bloc: ^9.1.0 #For state management
  intl: ^0.20.2 #For date and time formatting
  webview_flutter: ^4.10.0 #For showing source in webview
  fancy_shimmer_image: ^2.0.3 #For caching Image and show shimmer while loading
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# assets:
#   - .env

# The following section is specific to Flutter packages.
flutter:
  assets:
    - .env
  uses-material-design: true
